servers:
  tesla:
    host: "http://192.168.1.47"
    location: "tesla"
    runtimes:
      vllm:
        port: 8005
        token: ""
        models: []
          # - Step-3.7-Flash
          # - Qwen3.6-27B-FP8
          # - Qwen3.6-27B-NVFP4
          # - gemma-4-31B-it-NVFP4
          # - Qwen3.6-35B-A3B
          # - Qwen3.6-35B-A3B-FP8
          # - Qwen3.6-27B-NVFP4
          # - gemma-4-31B-it
          # - Qwen3.6-27B-NVFP4
          # - Qwen3.6-35B-A3B-NVFP4
          # - diffusiongemma-26B-A4B-it-NVFP4
      vllm-gemma:
        port: 8006
        token: ""
        models:
          # - Qwen3.6-35B-A3B-NVFP4
          # - Gemma4-26B-Uncensored
          # - gemma-4-31B-it-NVFP4
          # - gemma-4-31B-it
          # - Qwen3.6-35B-A3B-FP8
          # - Qwen3.6-27B-NVFP4
          - Gemma-4-26B-A4B-NVFP4
      llama-server:
        port: 8000
        token: ""
        models: []
          # - gemma-4-12b-it-UD-Q4_K_XL
          # - gemma-4-E4B-it-UD-Q8_K_XL
      # llama-server-gemma:
      #   port: 8001
      #   token: ""
      #   models:
      #     - unsloth/gemma-4-12B-it-qat-GGUF:UD-Q4_K_XL
  macmini:
    host: "http://mac-mini.local"
    location: "mac-mini"
    runtimes:
      # llama-server:
      #   port: 8005
      #   token: "asdf"
      #   models: []
      #     # - LFM2.5-8B-A1B-Q8_0
      #     # - gemma-4-26B-A4B-it-UD-Q4_K_XL
      #     # - gemma-4-26B-A4B-it-UD-Q8_K_XL
      #     # - Qwen3.6-35B-A3B-UD-Q4_K_M
      # omlx:
      #   port: 8001
      #   token: "asdf"
      #   models: []
      #     # - mlx-community/LFM2.5-8B-A1B-MLX-4bit
      #     # - gemma-4-26B-A4B-it-MLX-4bit
      #     # - "Qwen3.6-35B-A3B-4bit"
      #     # - "Qwen3.6-35B-A3B-UD-MLX-4bit"
      mlx-lm:
        port: 8080
        token: ""
        models: []
          # - mlx-community/gemma-4-E4B-it-qat-4bit
          # - lmstudio-community/gemma-4-26B-A4B-it-QAT-MLX-4bit
          # - unsloth/Qwen3.6-35B-A3B-UD-MLX-4bit
          # - LiquidAI/LFM2.5-8B-A1B-MLX-4bit
          # - LiquidAI/LFM2.5-8B-A1B-MLX-8bit
          # - mlx-community/gemma-4-26b-a4b-it-4bit
          # - zecanard/gemma-4-26B-A4B-it-uncensored-abliterix-MLX-4bit-nvfp4
          # - culturerevolt/gemma-4-26B-A4B-it-ultra-uncensored-heretic-mlx-4Bit
      # ollama:
      #   port: 11434
      #   token: ""
      #   models: []
      #     # - qwen3.6:35b-a3b-coding-nvfp4
      #     # - qwen3.6:35b-a3b-mtp-q4_K_M
      #     # - maternion/lfm2.5:8b
      #     # - gemma4:26b-nvfp4
      #     # - gemma4:26b-a4b-it-q4_K_M
      lm-studio:
        port: 1234
        token: ""
        models:
          # - google/gemma-4-12b
          # - gemma-4-12b-it-mlx
          # - google/gemma-4-12b-qat
          - google/gemma-4-26b-a4b
          - mlx-community/gemma-4-26b-a4b-it-nvfp4
      vllm:
        port: 8000
        token: ""
        models: []
          # - mlx-community/gemma-4-26b-a4b-it-4bit
          # - mlx-community/gemma-4-26B-A4B-it-qat-nvfp4
